//Actions for get all timesheets
export const GET_TIMESHEETS_SUCCESS = 'GET_TIMESHEETS_SUCCESS';
export const GET_TIMESHEETS_PENDING = 'GET_TIMESHEETS_PENDING';
export const GET_TIMESHEETS_ERROR = 'GET_TIMESHEETS_ERROR';
// Actions for delete a timesheet
export const DELETE_TIMESHEET_ERROR = 'DELETE_TIMESHEET_ERROR';
export const DELETE_TIMESHEET_SUCCESS = 'DELETE_TIMESHEET_SUCCESS';
export const DELETE_TIMESHEET_PENDING = 'DELETE_TIMESHEET_PENDING';
// ACTIONS FOR MODALS
export const SET_INFO_FOR_FEEDBACK = 'SET_INFO_FOR_FEEDBACK';
export const SET_INFO_FOR_DELETE = 'SET_INFO_FOR_DELETE';
export const SHOW_DELETE_MESSAGE = 'SHOW_DELETE_MESSAGE';
export const SHOW_FEEDBACK_MESSAGE = 'SHOW_FEEDBACK_MESSAGE';
//ACTIONS FOR FORM
export const ADD_OR_EDIT_TIMESHEET_ERROR = 'ADD_OR_EDIT_TIMESHEET_ERROR';
export const ADD_OR_EDIT_TIMESHEET_PENDING = 'ADD_OR_EDIT_TIMESHEET_PENDING';
export const ADD_OR_EDIT_TIMESHEET_SUCCESS = 'ADD_OR_EDIT_TIMESHEET_SUCCESS';
//ACTIONS FOR GETTIMESHEET
export const SELECTED_TIMESHEET = 'SELECTED_TIMESHEET';
