// ACTIONS FOR GET ALL TIMESHEETS
export const GET_TIMESHEETS_SUCCESS = 'GET_TIMESHEETS_SUCCESS';
export const GET_TIMESHEETS_PENDING = 'GET_TIMESHEETS_PENDING';
export const GET_TIMESHEETS_ERROR = 'GET_TIMESHEETS_ERROR';
// ACTIONS FOR DELETE A TIMESHEET
export const DELETE_TIMESHEET_ERROR = 'DELETE_TIMESHEET_ERROR';
export const DELETE_TIMESHEET_SUCCESS = 'DELETE_TIMESHEET_SUCCESS';
export const DELETE_TIMESHEET_PENDING = 'DELETE_TIMESHEET_PENDING';
// ACTIONS FOR MODALS
export const SET_INFO_FOR_FEEDBACK = 'SET_INFO_FOR_FEEDBACK';
export const SET_INFO_FOR_DELETE = 'SET_INFO_FOR_DELETE';
export const SHOW_DELETE_MESSAGE = 'SHOW_DELETE_MESSAGE';
export const SHOW_FEEDBACK_MESSAGE = 'SHOW_FEEDBACK_MESSAGE';
// ACTIONS FOR FORM
export const ADD_TIMESHEET_ERROR = 'ADD_TIMESHEET_ERROR';
export const ADD_TIMESHEET_PENDING = 'ADD_TIMESHEET_PENDING';
export const ADD_TIMESHEET_SUCCESS = 'ADD_TIMESHEET_SUCCESS';
// ACTIONS FOR EDIT
export const EDIT_TIMESHEET_ERROR = 'EDIT_TIMESHEET_ERROR';
export const EDIT_TIMESHEET_PENDING = 'EDIT_TIMESHEET_PENDING';
export const EDIT_TIMESHEET_SUCCESS = 'EDIT_TIMESHEET_SUCCESS';
// ACTIONS FOR GET A TIMESHEET
export const SELECTED_TIMESHEET = 'SELECTED_TIMESHEET';
// GET TIMESHEET BY ID
export const GET_TIMESHEET_BY_ID_ERROR = 'GET_TIMESHEET_BY_ID_ERROR';
export const GET_TIMESHEET_BY_ID_PENDING = 'GET_TIMESHEET_BY_ID_PENDING';
export const GET_TIMESHEET_BY_ID_SUCCESS = 'GET_TIMESHEET_BY_ID_SUCCESS';
// ACTIONS FOR EDIT HOURS ON A TIMESHEET
export const ADD_HOURS_TIMESHEET_SUCCESS = 'ADD_HOURS_TIMESHEET_SUCCESS';
export const ADD_HOURS_TIMESHEET_PENDING = 'ADD_HOURS_TIMESHEET_PENDING';
export const ADD_HOURS_TIMESHEET_ERROR = 'ADD_HOURS_TIMESHEET_ERROR';
// CLEAN STATE
export const CLEAN_SELECTED_TIMESHEET = 'CLEAN_SELECTED_TIMESHEET';
